volumes:
  scrapyd_data:

services:
  scrapyd:
    image: ${ORG_NAME}/${APP_SLUG}:${APP_VERSION}-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SCRAPYD_VERSION=${SCRAPYD_VERSION}
      target: development
    environment:
      SCRAPYD_USERNAME: ${SCRAPYD_USERNAME}
      SCRAPYD_PASSWORD: ${SCRAPYD_PASSWORD}
    volumes:
      - scrapyd_data:/var/lib/scrapyd
    ports:
      - "${APP_FORWARD_PORT}:${APP_PORT}"
    
