version: '3.8'

volumes:
  gwc_data:

services:
  geowebcache-prod:
    image: geowebcache-prod
    build:
      context: .
      target: geowebcache-prod
      args:
        IMAGE_VERSION: ${IMAGE_VERSION}
        GWC_VERSION: ${GWC_VERSION}
        WAR_URL: ${WAR_URL}
    environment:
      - INITIAL_MEMORY=${INITIAL_MEMORY}
      - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      - GWC_DATA_DIR=${GWC_DATA_DIR}
      - GWC_SEED_RETRY_COUNT=${GWC_SEED_RETRY_COUNT}
      - GWC_SEED_RETRY_WAIT=${GWC_SEED_RETRY_WAIT}
      - GWC_SEED_ABORT_LIMIT=${GWC_SEED_ABORT_LIMIT}
      - GWC_INITIAL_SEED_THREAD_POOL=${GWC_INITIAL_SEED_THREAD_POOL}
      - GWC_MAXIMUM_SEED_THREAD_POOL=${GWC_MAXIMUM_SEED_THREAD_POOL}
      - GWS_ADMIN_USER=${GWS_ADMIN_USER}
      - GWS_ADMIN_PASSWORD=${GWS_ADMIN_PASSWORD}
    ports:
      - ${GWC_PORT}:8080
    restart: on-failure
    entrypoint: [ "/app/entrypoint.sh" ]
    command: [ "catalina.sh", "run" ]
    volumes:
      - gwc_data:/app/geowebcache/data_dir
